version: '3.7'

services:
  go-fiber:
    container_name: go-fiber
    build:
      dockerfile: docker/Dockerfile
      context: .
    restart: always
    ports:
      - "7304:8080"
    volumes:
      - ./:/app
    environment:
      APP_ENV: local
    networks:
      - network-go-fiber
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - network-go-fiber
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - network-go-fiber

networks:
  network-go-fiber:
    external: false
    name: network-go-fiber