name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create env file
        run: |
          cp .env.production .env
          cat > .env << EOF
          ${{ secrets.ENV }}
          EOF
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "patzy-official-api" #Must be unique in Heroku
          heroku_email: "13_oy@hotmail.co.th"
          healthcheck: "https://patzy-official-api.herokuapp.com/health"
          checkstring: "ok"
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          APP_ENV: "production"
          APP_URL: "https://patzy-official-api.herokuapp.com"
          REPEAT: 10
          TAG_VERSION: ${PUSH_TAG_VERSION}"
